AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Deploy the backend services of WebAR prototype using SAM template.yaml
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Parameters:
  AWSRegionParam:
    Description: Region in which AWS resources are deployed
    Type: String
    Default: eu-central-1
  SensorDataDDBTablename: 
    Description: Name of dynamodb table storing sensor data
    Type: String
    Default: webar-ddb-sensordata2
  WateringHistoryDDBTablename:
    Description: Name of dynamodb table storing watering history
    Type: String
    Default: webar-ddb-wateringhistory2
  SensorDataSelectFunctionName:
    Description: Name of lambda function querying sensor data from ddb
    Type: String
    Default: webar-lambda-sensordataselect222
  WaterMeSelectFunctionName:
    Description: Name of lambda function querying watering records from ddb
    Type: String
    Default: webar-lambda-watermeselect2
  WaterMeInsertFunctionName:
    Description: Name of lambda function inserting a new watering record to ddb
    Type: String
    Default: webar-lambda-watermeinsert2
  SensorDataSelectFunctionRoleName:
    Description: Name of IAM role attached to lambda function querying sensor data from ddb
    Type: String
    Default: webar-role-lambdasensordataselect
  WaterMeSelectFunctionRoleName:
    Description: Name of IAM role attached to lambda function querying watering records from ddb
    Type: String
    Default: webar-role-lambdawatermeselect
  WaterMeInsertFunctionRoleName:
    Description: Name of IAM role attached to lambda function inserting a new watering record to ddb
    Type: String
    Default: webar-role-lambdawatermeinsert
  SensorDataSelectFunctionBasicExecutionPolicyName:
    Description: Name of IAM policy attached to lambda function querying sensor data from ddb
    Type: String
    Default: webar-policy-lambdasensordataselectbasicexecution
  SensorDataSelectFunctionDDBExecutionPolicyName:
    Description: Name of IAM policy attached to lambda function querying sensor data from ddb
    Type: String
    Default: webar-policy-lambdasensordataselectddbexecution
  WaterMeSelectFunctionBasicExecutionPolicyName:
    Description: Name of IAM policy attached to lambda function querying watering records from ddb
    Type: String
    Default: webar-policy-lambdawatermeselectbasicexecution
  WaterMeSelectFunctionDDBExecutionPolicyName:
    Description: Name of IAM policy attached to lambda function querying watering records from ddb
    Type: String
    Default: webar-policy-lambdawatermeselectddbexecution
  WaterMeInsertFunctionBasicExecutionPolicyName:
    Description: Name of IAM policy attached to lambda function inserting a new watering record to ddb
    Type: String
    Default: webar-policy-lambdawatermeinsertbasicexecutionpolicy
  WaterMeInsertFunctionDDBExecutionPolicyName:
    Description: Name of IAM policy attached to lambda function querying sensor data from ddb
    Type: String
    Default: webar-policy-lambdawatermeinsertddbexecution
  CloudFrontDistributionEndpoint:
    Description: URL of CloudFront distribution endpoint acting as CDN and serving frontend's static HTML, CSS, and JS
    Type: String
    Default: "*"
  
Resources:
  ##########################################################################
  #   DynamoDB                                                             #
  ##########################################################################
  SensorDataDDB:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: sensorId
          AttributeType: N
        - AttributeName: timeEpoch
          AttributeType: N
      KeySchema:
        - AttributeName: sensorId
          KeyType: HASH
        - AttributeName: timeEpoch
          KeyType: RANGE
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: !Ref SensorDataDDBTablename
      Tags: 
        - Key: project
          Value: webar
  SensorDataDDBWriteCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 10
      MinCapacity: 1
      ResourceId: !Join
        - /
        - - table
          - !Ref SensorDataDDB
      RoleARN: !GetAtt SensorDataDDBScalingRole.Arn
      ScalableDimension: dynamodb:table:WriteCapacityUnits
      ServiceNamespace: dynamodb
  SensorDataDDBScalingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - application-autoscaling.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "dynamodb:DescribeTable"
                  - "dynamodb:UpdateTable"
                  - "cloudwatch:PutMetricAlarm"
                  - "cloudwatch:DescribeAlarms"
                  - "cloudwatch:GetMetricStatistics"
                  - "cloudwatch:SetAlarmState"
                  - "cloudwatch:DeleteAlarms"
                Resource: "*"
  SensorDataDDBWriteScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: SensorDataDDBWriteAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref SensorDataDDBWriteCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization
  SensorDataDDBReadCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 10
      MinCapacity: 1
      ResourceId: !Join
        - /
        - - table
          - !Ref SensorDataDDB
      RoleARN: !GetAtt SensorDataDDBScalingRole.Arn
      ScalableDimension: dynamodb:table:ReadCapacityUnits
      ServiceNamespace: dynamodb
  SensorDataDDBReadScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: SensorDataDDBReadAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref SensorDataDDBReadCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBReadCapacityUtilization

  WateringHistoryDDB:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: plantId
          AttributeType: N
        - AttributeName: timeEpoch
          AttributeType: N
      KeySchema:
        - AttributeName: plantId
          KeyType: HASH
        - AttributeName: timeEpoch
          KeyType: RANGE
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: !Ref WateringHistoryDDBTablename
      Tags: 
        - Key: project
          Value: webar
  WateringHistoryDDBWriteCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 10
      MinCapacity: 1
      ResourceId: !Join
        - /
        - - table
          - !Ref WateringHistoryDDB
      RoleARN: !GetAtt WateringHistoryDDBScalingRole.Arn
      ScalableDimension: dynamodb:table:WriteCapacityUnits
      ServiceNamespace: dynamodb
  WateringHistoryDDBScalingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - application-autoscaling.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "dynamodb:DescribeTable"
                  - "dynamodb:UpdateTable"
                  - "cloudwatch:PutMetricAlarm"
                  - "cloudwatch:DescribeAlarms"
                  - "cloudwatch:GetMetricStatistics"
                  - "cloudwatch:SetAlarmState"
                  - "cloudwatch:DeleteAlarms"
                Resource: "*"
  WateringHistoryDDBWriteScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: WateringHistoryDDBWriteAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref WateringHistoryDDBWriteCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization
  WateringHistoryDDBReadCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 10
      MinCapacity: 1
      ResourceId: !Join
        - /
        - - table
          - !Ref WateringHistoryDDB
      RoleARN: !GetAtt WateringHistoryDDBScalingRole.Arn
      ScalableDimension: dynamodb:table:ReadCapacityUnits
      ServiceNamespace: dynamodb
  WateringHistoryDDBReadScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: WateringHistoryDDBReadAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref WateringHistoryDDBReadCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBReadCapacityUtilization

  ##########################################################################
  #   Lambda                                                               #
  ##########################################################################
  SensorDataSelectFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: webar-lambda-sensordataselect/
      Handler: app.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      FunctionName: !Ref SensorDataSelectFunctionName
      Tags:
        project: webar
      Environment:
        Variables:
          DDBTABLENAME: !Ref SensorDataDDB
          AWSREGION: !Ref AWSRegionParam
      Role: !GetAtt SensorDataSelectFunctionRole.Arn
      FunctionUrlConfig:
        AuthType: NONE
        Cors: 
            AllowMethods: 
              - POST
            AllowHeaders:
              - content-type
            AllowOrigins: 
              - "https://d287cl5btunnv2.cloudfront.net"

  WaterMeSelectFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: webar-lambda-watermeselect/
      Handler: app.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      FunctionName: !Ref WaterMeSelectFunctionName
      Tags:
        project: webar
      Environment:
        Variables:
          DDBTABLENAME: !Ref WateringHistoryDDB
          AWSREGION: !Ref AWSRegionParam
      Role: !GetAtt WaterMeSelectFunctionRole.Arn
      FunctionUrlConfig:
        AuthType: NONE
        Cors: 
            AllowMethods: 
              - POST
            AllowHeaders:
              - content-type
            AllowOrigins: 
              - "https://d287cl5btunnv2.cloudfront.net"

  WaterMeInsertFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: webar-lambda-watermeinsert/
      Handler: app.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      FunctionName: !Ref WaterMeInsertFunctionName
      Tags:
        project: webar
      Environment:
        Variables:
          DDBTABLENAME: !Ref WateringHistoryDDB
          AWSREGION: !Ref AWSRegionParam
      Role: !GetAtt WaterMeInsertFunctionRole.Arn
      FunctionUrlConfig:
        AuthType: NONE
        Cors: 
            AllowMethods: 
              - POST
            AllowHeaders:
              - content-type
            AllowOrigins: 
              - !Ref CloudFrontDistributionEndpoint
  
  ##########################################################################
  #   IAM                                                                  #
  ##########################################################################
  SensorDataSelectFunctionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref SensorDataSelectFunctionRoleName
      Tags: 
        - Key: "project"
          Value: "webar"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Principal:
              Service: "lambda.amazonaws.com"
            Effect: Allow
            Action: "sts:AssumeRole"

  SensorDataSelectFunctionBasicExecutionPolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: !Ref SensorDataSelectFunctionBasicExecutionPolicyName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "logs:CreateLogGroup"
            Resource: "arn:aws:logs:eu-central-1:268357442233:*"
          - Effect: Allow
            Action: 
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: "arn:aws:logs:eu-central-1:268357442233:log-group:/aws/lambda/webar-lambda-sensordataselect2:*"
      Roles: 
        - !Ref SensorDataSelectFunctionRole

  SensorDataSelectFunctionDDBExecutionPolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: !Ref SensorDataSelectFunctionDDBExecutionPolicyName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "dynamodb:Query"
            Resource: !GetAtt SensorDataDDB.Arn
      Roles: 
        - !Ref SensorDataSelectFunctionRole

  WaterMeSelectFunctionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref WaterMeSelectFunctionRoleName
      Tags: 
        - Key: "project"
          Value: "webar"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Principal:
              Service: "lambda.amazonaws.com"
            Effect: Allow
            Action: "sts:AssumeRole"

  WaterMeSelectFunctionBasicExecutionPolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: !Ref WaterMeSelectFunctionBasicExecutionPolicyName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "logs:CreateLogGroup"
            Resource: "arn:aws:logs:eu-central-1:268357442233:*"
          - Effect: Allow
            Action: 
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: "arn:aws:logs:eu-central-1:268357442233:log-group:/aws/lambda/webar-lambda-watermeselect2:*"
      Roles: 
        - !Ref WaterMeSelectFunctionRole

  WaterMeSelectFunctionDDBExecutionPolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: !Ref WaterMeSelectFunctionDDBExecutionPolicyName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "dynamodb:Query"
            Resource: !GetAtt WateringHistoryDDB.Arn
      Roles: 
        - !Ref WaterMeSelectFunctionRole
  
  WaterMeInsertFunctionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref WaterMeInsertFunctionRoleName
      Tags: 
        - Key: "project"
          Value: "webar"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Principal:
              Service: "lambda.amazonaws.com"
            Effect: Allow
            Action: "sts:AssumeRole"

  WaterMeInsertFunctionBasicExecutionPolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: !Ref WaterMeInsertFunctionBasicExecutionPolicyName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "logs:CreateLogGroup"
            Resource: "arn:aws:logs:eu-central-1:268357442233:*"
          - Effect: Allow
            Action: 
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: "arn:aws:logs:eu-central-1:268357442233:log-group:/aws/lambda/webar-lambda-watermeinsert2:*"
      Roles: 
        - !Ref WaterMeInsertFunctionRole

  WaterMeInsertFunctionDDBExecutionPolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: !Ref WaterMeInsertFunctionDDBExecutionPolicyName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "dynamodb:PutItem"
            Resource: !GetAtt WateringHistoryDDB.Arn
      Roles: 
        - !Ref WaterMeInsertFunctionRole

Outputs:
  SensorDataSelectFunction:
    Description: "Query sensor data from ddb"
    Value: !GetAtt SensorDataSelectFunction.Arn
  WaterMeSelectFunction:
    Description: "Query watering history from ddb"
    Value: !GetAtt WaterMeSelectFunction.Arn
  WaterMeInsertFunction:
    Description: "Write watering record to ddb"
    Value: !GetAtt WaterMeInsertFunction.Arn
  SensorDataDDB:
    Description: "Dynamodb table storing sensor data"
    Value: !GetAtt SensorDataDDB.Arn